# permissions for end users to view chartpresets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chartpreset-viewer-role
rules:
- apiGroups:
  - charts.x-helm.dev
  resources:
  - chartpresets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.x-helm.dev
  resources:
  - chartpresets/status
  verbs:
  - get
