# permissions for end users to edit chartpresets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chartpreset-editor-role
rules:
- apiGroups:
  - charts.x-helm.dev
  resources:
  - chartpresets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.x-helm.dev
  resources:
  - chartpresets/status
  verbs:
  - get
